name: CI & CD

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

# Reference
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

jobs:
  build:
    name: Test on python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        
    steps:
    - run: echo "Branch $GITHUB_REF"
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Make group jetson_stats
        sudo groupadd jetson_stats
        # Install test dependencies
        sudo ./tests/develop.sh -s
        # Upgrade pip
        sudo -H python -m pip install --upgrade pip
        # Install tox
        sudo -H pip install tox
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Test with tox
      run: |
        sudo tox -e py${{ matrix.python-version }}

  deploy:
    name: Deploy on PIP
    # needs: [build, docs]
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo -H python -m pip install --upgrade pip
        sudo -H pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        sudo python setup.py sdist
        twine upload dist/*
